name: Emscripten development build

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"
    paths:
      # This action only runs on push when files affecting the build change
      - "**.cpp"
      - "**.h"
      - "**.glsl"
      - "**.cmake"
      - "**Lists.txt"
      - "**-emscripten.yml"
  workflow_dispatch:

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build_emscripten:
    name: Build and deploy emscripten webapp
    runs-on: macos-14

    steps:
      - name: Install dependencies
        run: |
          brew install ninja emscripten

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/cache@v4
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      # Setup caching of build artifacts to reduce total build time (only Linux and MacOS)
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2

      - name: Configure CMake
        run: |
          emcmake cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/build/deploy

      - name: Build
        run: cmake --build ${{github.workspace}}/build --parallel

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-emscripten
          path: |
            ${{github.workspace}}/build

      - name: CPack
        working-directory: ${{github.workspace}}/build
        run: |
          cmake --install .
          mv deploy/HDRView.html deploy/index.html

      - name: Publish
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          destination_dir: dev
          publish_dir: ${{github.workspace}}/build/deploy
