name: Windows build

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"
    paths:
      # This action only runs on push when files affecting the build change
      - "**.cpp"
      - "**.h"
      - "**.glsl"
      - "**.cmake"
      - "**Lists.txt"
      - "**-windows.yml"
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.config.name }} (${{ matrix.buildtype }})
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        buildtype: [Release, Debug]
        config:
          - { name: "Windows", os: windows-latest }

    steps:
      - name: Install dependencies
        run: |
          pip install Pillow
          choco install libjpeg-turbo

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.buildtype }} -DCMAKE_POLICY_DEFAULT_CMP0135=NEW -DHDRVIEW_ENABLE_HEIF=ON -DHDRVIEW_ENABLE_JPEGXL=ON -DHDRVIEW_ENABLE_UHDR=ON -DUHDR_BUILD_DEPS=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build --parallel --config ${{ matrix.buildtype }} --verbose

      - name: Checking that HDRView runs
        working-directory: ${{github.workspace}}
        run: ./build/${{ matrix.buildtype }}/HDRView.exe --help

      - name: Copy files for archiving
        working-directory: ${{github.workspace}}/build
        run: |
          cmake -E copy_directory assets deploy/assets/
          cmake -E copy ${{ matrix.buildtype }}/HDRView.exe deploy/

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.config.os }}-${{ matrix.buildtype }}
          path: |
            ${{github.workspace}}/build/deploy
